server:
  port: 8081

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 3000

logging:
  level:
    root: WARN
    back.kalender: INFO
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
